
package iac.opdracht1iac;

import javax.xml.ws.WebFault;
import iac.error.Averageerr;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "averageerr", targetNamespace = "http://iac/error")
public class AverageError
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Averageerr faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AverageError(String message, Averageerr faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AverageError(String message, Averageerr faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: iac.error.Averageerr
     */
    public Averageerr getFaultInfo() {
        return faultInfo;
    }

}
